name: On tag

on:
  push:
    tags: 
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  VERSION_REF: ${GITHUB_REF}

jobs:
  check-branch:
    name: 'Check triggered branch'
    runs-on: ubuntu-22.04
    steps:
      - name: 'Exit if it is not on main branch'
        if: endsWith(github.event.base_ref, 'main') == false
        run: exit -1

  install-dependencies:
    needs: [check-branch]
    name: Install dependencies
    uses: ./.github/workflows/install_dependencies.yml
  
  qa:
    name: QA
    needs: [install-dependencies]
    uses: ./.github/workflows/qa.yml

  publish:
    name: Containerizing
    needs: [qa, version-parser]
    uses: ./.github/workflows/containerizing.yml
    secrets:
      NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
