name: On tag

on:
  push:
    tags: 
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  VERSION_REF: ${GITHUB_REF}

jobs:
  check-branch:
    name: 'Check triggered branch'
    runs-on: ubuntu-22.04
    steps:
      - name: 'Exit if it is not on main branch'
        if: endsWith(github.event.base_ref, 'main') == false
        run: exit -1

  install-dependencies:
    needs: [check-branch]
    name: Install dependencies
    uses: ./.github/workflows/install_dependencies.yml
  
  qa:
    name: QA
    needs: [install-dependencies]
    uses: ./.github/workflows/qa.yml

  publish:
    name: Containerizing
    needs: [qa]
    uses: ./.github/workflows/publish_library.yml
    secrets:
      NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
